-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "QRTokenUsage" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "usedAt" SET DATA TYPE TIMESTAMP(3);
